name: Rust Build ğŸ› ï¸

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout âœ…
        uses: actions/checkout@v4
      - name: Set up Rust ğŸ’»
        uses: dtolnay/rust-toolchain@stable
      - name: Cache Cargo ğŸ“¦
        uses: Swatinem/rust-cache@v2
      - name: Build ğŸ”§
        run: cargo build --verbose
